services:
  hueat-database:
    image: postgres:18.1-alpine
    restart: unless-stopped
    ports:
      - 54322:5432
    volumes:
      - ./volumes/hueat-database:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hueat}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-iUkcBQj2o_PpfX*uaXx7}
      POSTGRES_DB: ${POSTGRES_DB:-hueat}
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${POSTGRES_USER:-hueat} -d ${POSTGRES_DB:-hueat} -c 'SELECT 1' > /dev/null 2>&1"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - hueat-network

  hueat-webapp:
    image: lcastelli88/backend-webapp:latest
    restart: unless-stopped
    depends_on:
      hueat-database:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST:-hueat-database}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME:-hueat}
      DB_PASSWORD: ${DB_PASSWORD:-iUkcBQj2o_PpfX*uaXx7}
      DB_NAME: ${DB_NAME:-hueat}
      DB_SSL_MODE: ${DB_SSL_MODE:-disable}
      DB_LOG_SLOW_QUERY_THRESHOLD: ${DB_LOG_SLOW_QUERY_THRESHOLD:-1}
      APP_PORT: ${APP_PORT:-8001}
      APP_MODE: ${APP_MODE:-release}
      APP_CORS_ORIGIN: ${APP_CORS_ORIGIN:-*}
      PRINTER_ENABLED: ${PRINTER_ENABLED:-true}
      SEARCH_RELEVANCE_THRESHOLD: ${SEARCH_RELEVANCE_THRESHOLD:-0.05}
      PUBSUB_PERSIST_EVENTS_ON_DB: ${PUBSUB_PERSIST_EVENTS_ON_DB:-true}
      PUBSUB_PERSIST_EVENTS_RETENTION_DAYS: ${PUBSUB_PERSIST_EVENTS_RETENTION_DAYS:-1}
      PUBSUB_SYNC_MODE: ${PUBSUB_SYNC_MODE:-false}
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET:-ef1522b2795ee160c75900c181bd64cdc11160ef148b6bb906a4d44b900f68b4}
      AUTH_JWT_ACCESS_TOKEN_DURATION: ${AUTH_JWT_ACCESS_TOKEN_DURATION:-600}
      AUTH_JWT_REFRESH_TOKEN_DURATION: ${AUTH_JWT_REFRESH_TOKEN_DURATION:-86400}
    healthcheck:
      test: >
        sh -c 'wget -S -q  -O -  http://127.0.0.1:8001/api/v1/health-check 2>&1 >/dev/null | grep "200 OK"'
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - hueat-network

  hueat-migrate:
    image: lcastelli88/backend-migrate:latest
    restart: no
    depends_on:
      hueat-database:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST:-hueat-database}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME:-hueat}
      DB_PASSWORD: ${DB_PASSWORD:-iUkcBQj2o_PpfX*uaXx7}
      DB_NAME: ${DB_NAME:-hueat}
      DB_SSL_MODE: ${DB_SSL_MODE:-disable}
    networks:
      - hueat-network

  hueat-cli:
    image: lcastelli88/backend-cli:latest
    restart: no
    depends_on:
      hueat-webapp:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST:-hueat-database}
      DB_PORT: ${DB_PORT:-5432}
      DB_USERNAME: ${DB_USERNAME:-hueat}
      DB_PASSWORD: ${DB_PASSWORD:-iUkcBQj2o_PpfX*uaXx7}
      DB_NAME: ${DB_NAME:-hueat}
      DB_SSL_MODE: ${DB_SSL_MODE:-disable}
      DB_LOG_SLOW_QUERY_THRESHOLD: ${DB_LOG_SLOW_QUERY_THRESHOLD:-1}
      APP_PORT: ${APP_PORT:-8001}
      APP_MODE: ${APP_MODE:-release}
      APP_CORS_ORIGIN: ${APP_CORS_ORIGIN:-*}
      PRINTER_ENABLED: ${PRINTER_ENABLED:-true}
      SEARCH_RELEVANCE_THRESHOLD: ${SEARCH_RELEVANCE_THRESHOLD:-0.05}
      PUBSUB_PERSIST_EVENTS_ON_DB: ${PUBSUB_PERSIST_EVENTS_ON_DB:-true}
      PUBSUB_PERSIST_EVENTS_RETENTION_DAYS: ${PUBSUB_PERSIST_EVENTS_RETENTION_DAYS:-1}
      PUBSUB_SYNC_MODE: ${PUBSUB_SYNC_MODE:-false}
      AUTH_JWT_SECRET: ${AUTH_JWT_SECRET:-ef1522b2795ee160c75900c181bd64cdc11160ef148b6bb906a4d44b900f68b4}
      AUTH_JWT_ACCESS_TOKEN_DURATION: ${AUTH_JWT_ACCESS_TOKEN_DURATION:-600}
      AUTH_JWT_REFRESH_TOKEN_DURATION: ${AUTH_JWT_REFRESH_TOKEN_DURATION:-86400}
    networks:
      - hueat-network

  hueat-frontend:
    image: lcastelli88/frontend-webapp:latest
    restart: unless-stopped
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL:-https://hueat.local}
    healthcheck:
      test: ["CMD", "nginx", "-v"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - hueat-network

  hueat-caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DOMAIN: ${DOMAIN:-hueat.local}
    depends_on:
      - hueat-frontend
      - hueat-webapp
    networks:
      - hueat-network

networks:
  hueat-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
